### ISSUE TITLE
New features in v0.0.4

### ISSUE THREAD

**Issue by mariot7** [mariot7/Decorative-Styles#7]
Here's a list of all the changes that are coming in update v0.0.4:

- [x] New Carved Stone Block 3 
- [x] Re-texture Rusty Flake
- [x] Re-texture Jungle Clay
- [x] Re-texture White Brick
- [x] Re-texture White Cobblestone - see #1
- [x] Re-texture White Mossy Cobblestone - see #1
- [x] Re-texture White Stone - see #1
- [x] Re-texture Jungle Polished Stone - see #1 
- [x] Re-texture Jail Glass Block

**Comment by mariot7** [comment]
Version 0.0.4 of the mod is now released for Minecraft 1.7.10, 1.8 and 1.8.9!
